env:
  commonjs: true
  es6: true
  node: true
  jest: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  IR: readonly
parserOptions:
  ecmaVersion: 3
  sourceType: "script"
rules:
  no-var: 0
  no-unused-vars: 0
  one-var: 0
  one-var-declaration-per-line: 0
  vars-on-top: 0 # should be 2 for new projects
  no-use-before-define: 0
  no-nested-ternary: 0
  no-param-reassign: 0
  no-bitwise: 0
  prefer-template: 0
  prefer-arrow-callback: 0
  prefer-destructuring: 0
  prefer-rest-params: 0
  object-shorthand: 0
  no-invalid-this: 2
  block-scoped-var: 0
  no-extend-native: 0
  func-names: 0
  space-before-function-paren: ["error", "never"]
  max-len: ["error", 120, { "ignoreComments": true, "ignoreStrings": true, "ignoreRegExpLiterals": true }]
  no-underscore-dangle: 0
  no-plusplus: 0
  comma-dangle: ["error", "never"]
